---
application:
  name: "tg-vc-userbot"
  project: "tg-vc-userbot"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "tg-vc-userbot"
  version: "4.4"
routers:
- name: "main-tg-vc-userbot"
  routes:
  - application_name: "tg-vc-userbot"
    paths:
    - "/*"
